#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Apr 08 19:46:03 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 43c36e4ddc264616b9001301cfc5f78b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tbMemPrograma_behav xil_defaultlib.tbMemPrograma -log elaborate.log"
xelab -wto 43c36e4ddc264616b9001301cfc5f78b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tbMemPrograma_behav xil_defaultlib.tbMemPrograma -log elaborate.log

