#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 07 19:54:26 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 690c8b42ffaa474283d7ec1928f807f4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tbMemoria_behav xil_defaultlib.tbMemoria -log elaborate.log"
xelab -wto 690c8b42ffaa474283d7ec1928f807f4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tbMemoria_behav xil_defaultlib.tbMemoria -log elaborate.log

