#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jun 24 22:50:08 CDT 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto decefad39d2749f1b0180923ad4fae2c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot arquitectura_TB_func_synth xil_defaultlib.arquitectura_TB -log elaborate.log"
xelab -wto decefad39d2749f1b0180923ad4fae2c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot arquitectura_TB_func_synth xil_defaultlib.arquitectura_TB -log elaborate.log

