#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 26 23:15:53 CDT 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6e232c873e8d4727a6e89af97e2ccb9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cartaASM_TB_behav xil_defaultlib.cartaASM_TB -log elaborate.log"
xelab -wto 6e232c873e8d4727a6e89af97e2ccb9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cartaASM_TB_behav xil_defaultlib.cartaASM_TB -log elaborate.log

