#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 24 19:38:31 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6a607fe057784158bf6104846482010a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot simuSumador_behav xil_defaultlib.simuSumador -log elaborate.log"
xelab -wto 6a607fe057784158bf6104846482010a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot simuSumador_behav xil_defaultlib.simuSumador -log elaborate.log

