#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 24 19:38:33 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim simuSumador_behav -key {Behavioral:sim_1:Functional:simuSumador} -tclbatch simuSumador.tcl -view /media/d3vcr4ck/externData/materias-Sem20_2/arquitecturaDeComputadoras/practica1/sumadorNFor/simuSumador_behav.wcfg -log simulate.log"
xsim simuSumador_behav -key {Behavioral:sim_1:Functional:simuSumador} -tclbatch simuSumador.tcl -view /media/d3vcr4ck/externData/materias-Sem20_2/arquitecturaDeComputadoras/practica1/sumadorNFor/simuSumador_behav.wcfg -log simulate.log

