#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 20 14:07:47 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim sumaNBits_func_synth -key {Post-Synthesis:sim_1:Functional:sumaNBits} -tclbatch sumaNBits.tcl -log simulate.log"
xsim sumaNBits_func_synth -key {Post-Synthesis:sim_1:Functional:sumaNBits} -tclbatch sumaNBits.tcl -log simulate.log

