#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 04 17:31:00 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ca0d053a8ccc418381a931301534cda3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot simAlumN_behav xil_defaultlib.simAlumN -log elaborate.log"
xelab -wto ca0d053a8ccc418381a931301534cda3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot simAlumN_behav xil_defaultlib.simAlumN -log elaborate.log

