#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri May 15 20:45:33 CDT 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 8336c061d3c64304b11900d1f06fce3a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot pilaHW_TB_behav xil_defaultlib.pilaHW_TB -log elaborate.log"
xelab -wto 8336c061d3c64304b11900d1f06fce3a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot pilaHW_TB_behav xil_defaultlib.pilaHW_TB -log elaborate.log

