#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Mar 30 16:37:56 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ad4f7e12f8a0484eaee193e6cd51b4fa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot archRegTB_behav xil_defaultlib.archRegTB -log elaborate.log"
xelab -wto ad4f7e12f8a0484eaee193e6cd51b4fa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot archRegTB_behav xil_defaultlib.archRegTB -log elaborate.log

